package controllers;

import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.util.ArrayList;

import javafx.event.ActionEvent;

import javafx.scene.input.MouseEvent;
import javafx.scene.layout.AnchorPane;
import javafx.stage.Stage;
import javafx.stage.StageStyle;
import utils.CompareOperator;
import javafx.scene.input.KeyEvent;

import javafx.scene.control.TableView;

import javafx.scene.control.TableColumn;

public class InvoicesController {
	@FXML
	private TableView tableInvoices;
	@FXML
	private TableColumn colOrder;
	@FXML
	private TableColumn colId;
	@FXML
	private TableColumn colCode;
	@FXML
	private TableColumn colOrderCode;
	@FXML
	private TableColumn colTotal;
	@FXML
	private TableColumn colPayment;
	@FXML
	private TableColumn colCreatedAt;
	@FXML
	private Button btnView;
	@FXML
	private Button btnDelete;
	@FXML
	private TextField tfInvoice;
	@FXML
	private AnchorPane viewDetails;

	// Event Listener on TableView[#tableInvoices].onMouseClicked
	@FXML
	public void getTableDataByClick(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button[#btnView].onAction
	@FXML
	public void viewAction(ActionEvent event) {
		// TODO Autogenerated
		showFormDetails();
		
	}
	public void showFormDetails() {
  		try {
  			
  			FXMLLoader root = new FXMLLoader(getClass().getResource("/views/invoice-details.fxml"));
  			viewDetails = root.load();
  			
  			//controller
  			InvoiceDetailsController controller = root.<InvoiceDetailsController>getController();
  		//	controller.loadDataUpdateById(this);
  			
  			Scene scene = new Scene(viewDetails, 600, 600);
  			Stage createStage = new Stage();
  			createStage.initStyle(StageStyle.UNDECORATED);
  			createStage.setScene(scene);
  			createStage.show();			
  			
  		} catch (Exception e) {
  			e.printStackTrace();
  		}
  	}
	
	
	
	// Event Listener on Button[#btnDelete].onAction
	@FXML
	public void deleteAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnClearAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#tfUser].onKeyTyped
	@FXML
	public void onSearch(KeyEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void addOrderAction(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void printAction(ActionEvent event) {
		// TODO Autogenerated
	}
}
